name: Emscripten build
run-name: ${{ gitea.actor }} is building newbase emscripten
on: [push]

jobs:
  Main-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mymindstorm/setup-emsdk@v14
      - name: Verify Emscripten installation
        run: emcc -v
      - name: "Setup Python and CMake"
        run: |
          python3 -m venv venv
          source venv/bin/activate
          which pip && which python
          pip install --upgrade pip
          pip install cmake~=3.5
          cmake --version
          echo "Installing script deps..."
          pip install -r scripts/requirements.txt
          env
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Configure 
        run: |
          env
          source venv/bin/activate 
          cmake -S . -B embuild -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      - name: Build
        run: |
          env
          source venv/bin/activate
          cmake --build embuild -j $(( $(nproc) - 1 ))
      - name: Upload build artifact
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: newbase_emscripten_${{ github.head_ref }}_${{ github.sha }}
          path: embuild
      - name: Rename demo html output file
        run: |
          mv embuild/demo/newbase_demo.html embuild/demo/index.html
      - name: Deploy demo to itch.io
        env:
          BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}
        run: |
          curl -L -o butler.zip https://github.com/itchio/butler/releases/latest/download/butler-linux-amd64.zip
          unzip butler.zip
          chmod +x linux-amd64/butler
          ITCH_IPV4=$(curl -4 -s "https://dns.google/resolve?name=upload.itch.io&type=A" | grep -o '"data":"[^"]*"' | head -1 | cut -d'"' -f4)
          echo "upload.itch.io IPv4: $ITCH_IPV4"
          echo "$ITCH_IPV4 upload.itch.io" | sudo tee -a /etc/hosts
          linux-amd64/butler push ./embuild/demo camarguinho/newbase-demo:webgl --userversion ${{ github.sha }}
