name: Emscripten build
run-name: ${{ gitea.actor }} is building newbase emscripten
on: [push]

jobs:
  Main-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mymindstorm/setup-emsdk@v14
      - name: Verify Emscripten installation
        run: emcc -v
      - name: "Setup Python and CMake"
        run: |
          python3 -m venv venv
          source venv/bin/activate
          which pip && which python
          pip install --upgrade pip
          pip install cmake~=3.5
          cmake --version
          echo "Installing script deps..."
          pip install -r scripts/requirements.txt
          env
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Configure 
        run: |
          env
          source venv/bin/activate 
          cmake -S . -B embuild -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      - name: Build
        run: |
          env
          source venv/bin/activate
          cmake --build embuild -j $(( $(nproc) - 1 ))
      - name: Package Release
        run: tar cvzf newbase_emscripten_${{ github.head_ref }}_${{ github.sha }}.tar.gz -C embuild .
      - name: Upload package
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: newbase_emscripten
          path: newbase_emscripten_${{ github.head_ref }}_${{ github.sha }}.tar.gz
