name: Emscripten build
run-name: ${{ gitea.actor }} is building newbase emscripten
on: [push]

jobs:
  Main-Build:
    runs-on: emscripten/emsdk:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: git submodule update --init --recursive
      - run: cmake -S . -B embuild -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      - run: cmake --build embuild -j $(( $(nproc) - 1 ))
