name: Flatpak Build
run-name: ${{ gitea.actor }} is building newbase for Flatpack 🐧
on: [push]

jobs:
  Main-Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Gather info and freeze Python deps
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install requirements-parser
          python3 ./scripts/flatpak-pip-generator.py --requirements-file ./scripts/requirements.txt -o ./demo/flatpak/python-build-deps
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        name: "Build"
        with:
          bundle: newbase_demo_${SHORT_SHA}.flatpak
          manifest-path: demo/flatpak/br.eng.camargo.newbase.demo.yml
          cache-key: flatpak-builder-${SHORT_SHA}
