name: Linux Build
run-name: ${{ gitea.actor }} is building newbase for Linux 🐧
on: [push]

jobs:
  Main-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup build deps
        run: |
          cat /etc/os-release
          sudo apt update
          sudo apt install -y build-essential git make \
            pkg-config cmake ninja-build libasound2-dev libpulse-dev \
            libaudio-dev libfribidi-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
            libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev
      - name: "Setup Python and CMake"
        run: |
          which python
          which python3
          python3 -m venv venv
          ls || echo hmmm
          ls venv || echo ooo
          source venv/bin/activate
          which pip && which python
          pip install --upgrade pip
          pip install cmake~=3.5
          cmake --version
          echo "Installing script deps..."
          pip install -r scripts/requirements.txt
          env
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Configure 
        run: |
          env
          source venv/bin/activate 
          cmake -S . -B build  -G Ninja -DCMAKE_BUILD_TYPE=Release -DNEWBASE_LTO=ON -DNEWBASE_FDO_FILES=ON
      - name: Build
        run: |
          env
          source venv/bin/activate
          cmake --build build -j $(( $(nproc) - 1 ))
      - name: Install
        run: |
          source venv/bin/activate
          cmake --install build --prefix build/install
      - name: Upload install artifact
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: newbase_linux_amd64_${{ github.head_ref }}_${{ github.sha }}
          path: build/install
