plugins {
     id 'com.android.application'
}

android {
    namespace "br.eng.camargo.newbase.demo"
    compileSdkVersion 35
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                arguments /*"--trace",*/ "-DNEWBASE_SDL_STATIC=OFF", "-DNEWBASE_ANDROID_MAIN=newbase_demo", "-DANDROID_PLATFORM=android-19", "-DANDROID_STL=c++_static"
                // abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
                abiFilters 'arm64-v8a', 'x86_64'
                targets "main"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    applicationVariants.all { variant ->
        tasks["merge${variant.name.capitalize()}Assets"]
            .dependsOn("externalNativeBuild${variant.name.capitalize()}")
    }
    if (!project.hasProperty('EXCLUDE_NATIVE_LIBS')) {
        sourceSets.main {
            jniLibs.srcDir 'libs'
        }
        externalNativeBuild {
            cmake {
                path '../../../CMakeLists.txt'
            }
        }

    }
    sourceSets.main {
        assets.srcDirs += ["./assets"]
    }
    tasks.register('reslink') {
        ant.symlink(externalNativeBuild.cmake.getBuildStagingDirectory() + "/demo/nb", "./aseets/nb")
    }
    lint {
        abortOnError false
    }
    afterEvaluate {
        android.sourceSets.main.assets.srcDirs.each{println it}
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
