plugins {
     id 'com.android.application'
}

android {
    namespace "br.eng.camargo.newbase.demo"
    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 33  // sets up -DANDROID_PLATFORM in CMake too
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                arguments /*"--trace",*/ "-DNEWBASE_SDL_STATIC=OFF", "-DNEWBASE_ANDROID_MAIN=newbase_demo", "-DANDROID_STL=c++_static", "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
                // abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
                targets "main"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets.main {
        jniLibs.srcDir 'libs'
    }
    externalNativeBuild {
        cmake {
            path '../../../CMakeLists.txt'
        }
    }

    sourceSets.main {
        assets.srcDirs += ["./assets"]
    }
    aaptOptions{
        // we may have assets beginning with _, which are ignored by default. Override.
        ignoreAssetsPattern  '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
    }
    lint {
        abortOnError false
    }
    afterEvaluate {
        android.sourceSets.main.assets.srcDirs.each{println it}
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
