# We have a conf/ and classes/ directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "newbase"
BBFILE_PATTERN_newbase = "^${LAYERDIR}/"
BBFILE_PRIORITY_newbase = "10"

LAYERDEPENDS_newbase = "core raspberrypi"
LAYERSERIES_COMPAT_newbase = "walnascar scarthgap"
