#!/usr/bin/env python3
"""
Parses TalkiePCM vocabulary headers and generates
include/newbase/audio/talkie_pcm_vocab.hpp.

Each unique word name maps to a null-terminated list of PCM data pointers
(one per ROM/voice variant that provides that word), plus a parallel list of
variant name strings (e.g. "sp2", "sp3") for display in the UI.
"""

import argparse
import re
import sys
from pathlib import Path
from collections import defaultdict

DEFAULT_HEADERS = ['Vocab_Special.h', 'Vocab_US_Large.h']


def parse_symbol(name):
    """Return (prefix, word) for a TalkiePCM symbol.

    sp2_ZERO   -> ("sp2",  "ZERO")
    spa_PAUSE1 -> ("spa",  "PAUSE1")
    spPAUSE1   -> ("sp",   "PAUSE1")
    zero       -> ("",     "zero")
    """
    m = re.match(r'^(sp\d+)_(.+)$', name)
    if m:
        return m.group(1), m.group(2)
    m = re.match(r'^(sp[a-z]+)_(.+)$', name)
    if m:
        return m.group(1), m.group(2)
    m = re.match(r'^(sp)([A-Z_].*)$', name)
    if m:
        return m.group(1), m.group(2)
    return '', name


def c_ident(word):
    """Make a word safe to use as part of a C identifier."""
    return re.sub(r'\W', '_', word)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--vocab-dir', required=True,
                    help='Path to TalkiePCM/src directory containing Vocab_*.h files')
    ap.add_argument('--output', required=True,
                    help='Path for the generated .hpp file')
    ap.add_argument('--headers', nargs='+', default=DEFAULT_HEADERS,
                    help='Vocab header filenames to parse (relative to --vocab-dir)')
    args = ap.parse_args()

    vocab_dir = Path(args.vocab_dir)
    out_path = Path(args.output)

    # word -> list of (symbol, prefix)  ordered by appearance
    word_variants = defaultdict(list)

    for header_name in args.headers:
        header_path = vocab_dir / header_name
        if not header_path.exists():
            print(f'WARNING: {header_path} not found, skipping', file=sys.stderr)
            continue
        text = header_path.read_text()
        for m in re.finditer(r'uint8_t\s+(\w+)\s*\[', text):
            sym = m.group(1)
            prefix, word = parse_symbol(sym)
            entry = (sym, prefix)
            if entry not in word_variants[word]:
                word_variants[word].append(entry)

    words = sorted(word_variants.keys())

    lines = []
    lines.append('// AUTO-GENERATED by scripts/generate_talkie_vocab.py — do not edit manually.\n')
    lines.append('// Re-run the script (or re-configure with NEWBASE_TALKIE_PCM=ON) to regenerate.\n')
    lines.append('#pragma once\n')
    lines.append('#ifdef NEWBASE_TALKIE_PCM\n')
    lines.append('\n')
    lines.append('#include <cstdint>\n')
    lines.append('#include <cstddef>\n')
    lines.append('\n')
    for h in args.headers:
        lines.append(f'#include <{h}>\n')
    lines.append('\n')
    lines.append('namespace nb {\n')
    lines.append('\n')
    lines.append('struct talkie_vocab_entry {\n')
    lines.append('    const char*            word;          // display name, e.g. "ZERO"\n')
    lines.append('    const uint8_t* const*  variants;      // null-terminated array of PCM data pointers\n')
    lines.append('    const char* const*     variant_names; // null-terminated, parallel to variants (e.g. "sp2")\n')
    lines.append('    size_t                 variant_count;\n')
    lines.append('};\n')
    lines.append('\n')
    lines.append('inline const talkie_vocab_entry* talkie_vocab_all(size_t& out_count)\n')
    lines.append('{\n')

    for word in words:
        variants = word_variants[word]
        safe     = c_ident(word)
        syms_str  = ', '.join(v[0] for v in variants) + ', nullptr'
        names_str = ', '.join(f'"{v[1]}"' for v in variants) + ', nullptr'
        lines.append(f'    static const uint8_t* const tv_{safe}_v[]  = {{ {syms_str} }};\n')
        lines.append(f'    static const char* const    tv_{safe}_vn[] = {{ {names_str} }};\n')

    lines.append('\n')
    lines.append('    static const talkie_vocab_entry TABLE[] = {\n')
    for word in words:
        variants = word_variants[word]
        safe     = c_ident(word)
        lines.append(f'        {{ "{word}", tv_{safe}_v, tv_{safe}_vn, {len(variants)} }},\n')
    lines.append('    };\n')
    lines.append('    out_count = sizeof(TABLE) / sizeof(TABLE[0]);\n')
    lines.append('    return TABLE;\n')
    lines.append('}\n')
    lines.append('\n')
    lines.append('} // namespace nb\n')
    lines.append('#endif // NEWBASE_TALKIE_PCM\n')

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(''.join(lines))
    print(f'[generate_talkie_vocab] {len(words)} words -> {out_path}')


if __name__ == '__main__':
    main()
