systems:
 render_simple:
    w: 1280
    h: 720
 audio:
    streams:
        - sfx
        - bgm
 script_lua: {}
resources:
 scanners:
 - type: "fs_raw"
   path: "./res/"
 - type: "title_storage"
   path: "/"
