systems:
  render_simple:
    #prefer: wayland
    w: 1280
    h: 720
  audio:
    bgm_gain: 0.8
    sfx_gain: 1.0
  script_lua: {}
  editor: {}
  input:
    default_actions: true
  clock: {}
  physics2d:
    world_scale: 50
  steam:
    app_id: 480
resources:
  scanners:
    - type: "fs_raw"
      path: "./res/"
    - type: "title_storage"
      path: "/"
