if(CMAKE_CROSSCOMPILING)
    message(STATUS "[tools] skipping host tools (cross-compiling)")
    return()
endif()

if(NEWBASE_DPI_TEST)
    add_executable(dpi_test src/etc/imgui_dpi_test.cpp ${IMGUI_SOURCES})
    target_link_libraries(dpi_test SDL3::SDL3)
    target_include_directories(dpi_test PRIVATE ${IMGUI_INCLUDES} src/ui)
    if(NEWBASE_WII)
        target_compile_definitions(dpi_test PRIVATE IMGUI_DISABLE_DEFAULT_SHELL_FUNCTIONS)
    endif()
endif()
