# this is meant to be a complete binary with all features,
# used to run game archives/folders with no fuss
# this is only worth doing when the engine is more mature
# for now all engine development happens with the demo

#add_executable(newbase_runner WIN32 
#    src/main.c)

#target_link_libraries(newbase_runner PRIVATE newbase)  