# our handling of Slang

if(NEWBASE_SLANG)

# Slang minimal build setup
if(NEWBASE_EMSCRIPTEN)
set(SLANG_LIB_TYPE STATIC CACHE STRING "" FORCE)
else()
set(SLANG_LIB_TYPE SHARED CACHE STRING "" FORCE)
endif()

# Disable external compilers (DXC, glslang)
set(SLANG_ENABLE_SLANG_GLSLANG OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_DXIL OFF CACHE BOOL "" FORCE)

# Disable LLVM for running shaders in CPU with JIT (not needed)
set(SLANG_SLANG_LLVM_FLAVOR DISABLE CACHE BOOL "" FORCE)

# Disable executables, servers, and tests
set(SLANG_ENABLE_SLANGC OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANGD OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANGI OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANGRT OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_GFX OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)

# some more settings, especially useful for Emscripten size
set(SLANG_ENABLE_AFTERMATH OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_CUDA OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_GFX OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SLANG_RHI OFF CACHE BOOL "" FORCE)
set(SLANG_ENABLE_SPLIT_DEBUG_INFO OFF CACHE BOOL "" FORCE)


add_subdirectory(vendored/slang EXCLUDE_FROM_ALL)

endif(NEWBASE_SLANG)
